"""v1

Revision ID: ecae86cf7fc9
Revises: 0c0650d38944
Create Date: 2024-12-23 23:02:31.636487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecae86cf7fc9'
down_revision: Union[str, None] = '0c0650d38944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('inx_proj_name', table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.drop_index('ix_projects_history_updated_at', table_name='projects_history')
    op.create_index(op.f('ix_projects_history_created_at'), 'projects_history', ['created_at'], unique=False)
    op.drop_column('projects_history', 'updated_at')
    op.drop_index('ix_subscriptions_history_updated_at', table_name='subscriptions_history')
    op.create_index(op.f('ix_subscriptions_history_created_at'), 'subscriptions_history', ['created_at'], unique=False)
    op.drop_column('subscriptions_history', 'updated_at')
    op.drop_index('ix_us_to_pr_history_updated_at', table_name='us_to_pr_history')
    op.create_index(op.f('ix_us_to_pr_history_created_at'), 'us_to_pr_history', ['created_at'], unique=False)
    op.drop_column('us_to_pr_history', 'updated_at')
    op.drop_index('inx_mid_name', table_name='users')
    op.drop_index('inx_surname', table_name='users')
    op.drop_index('inx_user_name', table_name='users')
    op.create_index(op.f('ix_users_mid_name'), 'users', ['mid_name'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    op.drop_index('ix_users_history_updated_at', table_name='users_history')
    op.create_index(op.f('ix_users_history_created_at'), 'users_history', ['created_at'], unique=False)
    op.drop_column('users_history', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_history', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("'9999-01-01 00:00:00'::timestamp without time zone"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_history_created_at'), table_name='users_history')
    op.create_index('ix_users_history_updated_at', 'users_history', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_mid_name'), table_name='users')
    op.create_index('inx_user_name', 'users', ['name'], unique=False)
    op.create_index('inx_surname', 'users', ['surname'], unique=False)
    op.create_index('inx_mid_name', 'users', ['mid_name'], unique=False)
    op.add_column('us_to_pr_history', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("'9999-01-01 00:00:00'::timestamp without time zone"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_us_to_pr_history_created_at'), table_name='us_to_pr_history')
    op.create_index('ix_us_to_pr_history_updated_at', 'us_to_pr_history', ['updated_at'], unique=False)
    op.add_column('subscriptions_history', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("'9999-01-01 00:00:00'::timestamp without time zone"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscriptions_history_created_at'), table_name='subscriptions_history')
    op.create_index('ix_subscriptions_history_updated_at', 'subscriptions_history', ['updated_at'], unique=False)
    op.add_column('projects_history', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("'9999-01-01 00:00:00'::timestamp without time zone"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_history_created_at'), table_name='projects_history')
    op.create_index('ix_projects_history_updated_at', 'projects_history', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index('inx_proj_name', 'projects', ['name'], unique=False)
    # ### end Alembic commands ###
